I18N.register({
  "en": {
    "title": "Folder Image Slideshow",
    "subtitle": "Pick a folder and play its images as a slideshow",
    "btn_select_folder": "Select Folder",
    "btn_pause": "Pause",
    "btn_resume": "Resume",
    "btn_reload": "Reload",
    "label_interval": "INTERVAL",
    "empty_no_folder": "Select a folder to begin the slideshow.",
    "empty_loading": "Loading images...",
    "empty_no_images": "No images found in the selected folder. Pick another folder or add some image files.",
    "empty_unsupported": "Your browser does not provide the folder-picker API. Use a recent Chromium-based browser served over HTTPS.",
    "empty_blocked": "Folder access is blocked in this context (typically an iframe or insecure origin). Open this page in a new top-level tab over HTTPS.",
    "empty_denied": "Permission to read the folder was denied. Click Select Folder to try again.",
    "empty_read_error": "Could not read the folder contents. The folder may have been moved or removed.",
    "empty_unknown": "An unexpected error occurred. Check the browser console for details.",
    "folder_count": "{n} images",
    "aria_main": "Folder image slideshow",
    "aria_select_folder": "Select folder",
    "aria_interval": "Slideshow interval in seconds",
    "aria_pause": "Pause or resume the slideshow",
    "aria_reload": "Reload images from the current folder"
  },
  "ko": {
    "title": "폴더 이미지 슬라이드쇼",
    "subtitle": "폴더를 선택하면 그 안의 이미지를 슬라이드쇼로 재생합니다",
    "btn_select_folder": "폴더 선택",
    "btn_pause": "일시정지",
    "btn_resume": "재생",
    "btn_reload": "다시 불러오기",
    "label_interval": "간격",
    "empty_no_folder": "슬라이드쇼를 시작하려면 폴더를 선택해 주세요.",
    "empty_loading": "이미지를 불러오는 중...",
    "empty_no_images": "선택한 폴더에 이미지가 없습니다. 다른 폴더를 선택하거나 이미지 파일을 추가해 주세요.",
    "empty_unsupported": "이 브라우저는 폴더 선택 API를 제공하지 않습니다. HTTPS 환경의 최신 Chromium 계열 브라우저에서 시도해 주세요.",
    "empty_blocked": "현재 환경(iframe 또는 비보안 오리진)에서는 폴더 접근이 차단되어 있습니다. 새 탭에서 HTTPS로 페이지를 열어 주세요.",
    "empty_denied": "폴더 접근 권한이 거부되었습니다. 폴더 선택 버튼을 눌러 다시 시도해 주세요.",
    "empty_read_error": "폴더 내용을 읽을 수 없습니다. 폴더가 이동되었거나 삭제되었을 수 있습니다.",
    "empty_unknown": "예상치 못한 오류가 발생했습니다. 브라우저 콘솔에서 자세한 내용을 확인해 주세요.",
    "folder_count": "이미지 {n}개",
    "aria_main": "폴더 이미지 슬라이드쇼",
    "aria_select_folder": "폴더 선택",
    "aria_interval": "슬라이드쇼 간격(초)",
    "aria_pause": "슬라이드쇼 일시정지/재생",
    "aria_reload": "현재 폴더에서 이미지 다시 불러오기"
  },
  "jp": {
    "title": "フォルダ画像スライドショー",
    "subtitle": "フォルダを選ぶと、その中の画像をスライドショー再生します",
    "btn_select_folder": "フォルダを選択",
    "btn_pause": "一時停止",
    "btn_resume": "再生",
    "btn_reload": "再読み込み",
    "label_interval": "間隔",
    "empty_no_folder": "スライドショーを開始するにはフォルダを選択してください。",
    "empty_loading": "画像を読み込み中...",
    "empty_no_images": "選択したフォルダに画像がありません。別のフォルダを選択するか、画像ファイルを追加してください。",
    "empty_unsupported": "このブラウザはフォルダ選択 API を提供していません。HTTPS 環境の最新 Chromium 系ブラウザで試してください。",
    "empty_blocked": "現在のコンテキスト(iframe または非セキュアな origin)ではフォルダアクセスがブロックされています。HTTPS の新しいタブでこのページを開いてください。",
    "empty_denied": "フォルダへのアクセス権限が拒否されました。フォルダ選択をクリックして再試行してください。",
    "empty_read_error": "フォルダの内容を読み取れません。フォルダが移動または削除された可能性があります。",
    "empty_unknown": "予期しないエラーが発生しました。詳細はブラウザのコンソールを確認してください。",
    "folder_count": "画像 {n}枚",
    "aria_main": "フォルダ画像スライドショー",
    "aria_select_folder": "フォルダを選択",
    "aria_interval": "スライドショーの間隔(秒)",
    "aria_pause": "スライドショーの一時停止/再生",
    "aria_reload": "現在のフォルダから画像を再読み込み"
  }
});
