I18N.init({
  "en": {
    "title": "JSON Visualizer",
    "visualization": "Visualization",
    "expand_all": "Expand All",
    "collapse_all": "Collapse All",
    "reset_layout": "Reset Layout",
    "fit_to_view": "Fit to View",
    "zoom_out": "Zoom Out",
    "zoom_in": "Zoom In",
    "empty_state": "Enter JSON on the right to visualize",
    "json_input": "JSON Input",
    "format": "Format",
    "sample": "Sample",
    "placeholder": "Paste or type JSON here...",
    "root": "Root",
    "child_count": "child: ",
    "null_value": "null",
    "too_many_nodes": "Too many nodes ({count}). Limit is 500. Simplify the JSON to visualize."
  },
  "ko": {
    "title": "JSON 시각화",
    "visualization": "시각화",
    "expand_all": "모두 펼치기",
    "collapse_all": "모두 접기",
    "reset_layout": "레이아웃 초기화",
    "fit_to_view": "화면에 맞추기",
    "zoom_out": "축소",
    "zoom_in": "확대",
    "empty_state": "오른쪽에 JSON을 입력하면 시각화됩니다",
    "json_input": "JSON 입력",
    "format": "포맷",
    "sample": "샘플",
    "placeholder": "여기에 JSON을 붙여넣거나 입력하세요...",
    "root": "루트",
    "child_count": "하위: ",
    "null_value": "null",
    "too_many_nodes": "노드가 너무 많습니다 ({count}). 최대 500개입니다. JSON을 간소화해주세요."
  },
  "jp": {
    "title": "JSONビジュアライザー",
    "visualization": "ビジュアライズ",
    "expand_all": "すべて展開",
    "collapse_all": "すべて折りたたむ",
    "reset_layout": "レイアウトリセット",
    "fit_to_view": "画面に合わせる",
    "zoom_out": "縮小",
    "zoom_in": "拡大",
    "empty_state": "右側にJSONを入力すると視覚化されます",
    "json_input": "JSON入力",
    "format": "フォーマット",
    "sample": "サンプル",
    "placeholder": "ここにJSONを貼り付けるか入力してください...",
    "root": "ルート",
    "child_count": "子要素: ",
    "null_value": "null",
    "too_many_nodes": "ノードが多すぎます（{count}）。上限は500です。JSONを簡略化してください。"
  }
});
