I18N.register({
  "en": {
    "title": "QR Code Generator",
    "subtitle": "Type text to automatically generate a QR code",
    "qr_placeholder": "Enter text below",
    "text_label": "TEXT",
    "input_placeholder": "Enter a URL or text...",
    "error_lib": "Failed to load the QR library.",
    "error_generate": "Could not generate QR code: ",
    "recent_title": "Recent",
    "recent_empty": "No recent items",
    "save_btn": "Save",
    "download_label": "DOWNLOAD",
    "theme_light": "Light",
    "theme_dark": "Dark",
    "aria_main": "QR code generator",
    "aria_qr_area_empty": "QR code preview (empty)",
    "aria_qr_area_for": "QR code for: {text}",
    "aria_char_count": "Character count",
    "aria_save_btn": "Save current text to recent list",
    "aria_recent_panel": "Recent QR codes",
    "aria_recent_item": "Load recent: {text}",
    "aria_download_group": "Download QR code",
    "aria_download_theme": "Download color theme",
    "aria_download_png": "Download as PNG",
    "aria_download_jpg": "Download as JPG",
    "aria_download_svg": "Download as SVG",
    "hint_save_shortcut": "Press Control or Command plus Enter to save.",
    "announce_saved": "Saved to recent list",
    "announce_loaded": "Loaded recent item"
  },
  "ko": {
    "title": "QR 코드 생성기",
    "subtitle": "텍스트를 입력하면 QR 코드가 자동으로 생성됩니다",
    "qr_placeholder": "아래에 텍스트를 입력하세요",
    "text_label": "텍스트",
    "input_placeholder": "URL 또는 텍스트를 입력하세요...",
    "error_lib": "QR 라이브러리를 불러오지 못했습니다.",
    "error_generate": "QR 코드를 생성할 수 없습니다: ",
    "recent_title": "최근",
    "recent_empty": "최근 항목이 없습니다",
    "save_btn": "저장",
    "download_label": "다운로드",
    "theme_light": "라이트",
    "theme_dark": "다크",
    "aria_main": "QR 코드 생성기",
    "aria_qr_area_empty": "QR 코드 미리보기 (비어 있음)",
    "aria_qr_area_for": "QR 코드: {text}",
    "aria_char_count": "글자수",
    "aria_save_btn": "현재 텍스트를 최근 목록에 저장",
    "aria_recent_panel": "최근 QR 코드 목록",
    "aria_recent_item": "최근 항목 불러오기: {text}",
    "aria_download_group": "QR 코드 다운로드",
    "aria_download_theme": "다운로드 색상 테마",
    "aria_download_png": "PNG로 다운로드",
    "aria_download_jpg": "JPG로 다운로드",
    "aria_download_svg": "SVG로 다운로드",
    "hint_save_shortcut": "저장하려면 Ctrl 또는 Command 키와 Enter 키를 누르세요.",
    "announce_saved": "최근 목록에 저장되었습니다",
    "announce_loaded": "최근 항목을 불러왔습니다"
  },
  "jp": {
    "title": "QRコードジェネレーター",
    "subtitle": "テキストを入力すると自動的にQRコードが生成されます",
    "qr_placeholder": "下にテキストを入力してください",
    "text_label": "テキスト",
    "input_placeholder": "URLまたはテキストを入力...",
    "error_lib": "QRライブラリを読み込めませんでした。",
    "error_generate": "QRコードを生成できません: ",
    "recent_title": "最近",
    "recent_empty": "最近の項目がありません",
    "save_btn": "保存",
    "download_label": "ダウンロード",
    "theme_light": "ライト",
    "theme_dark": "ダーク",
    "aria_main": "QRコードジェネレーター",
    "aria_qr_area_empty": "QRコードプレビュー (空)",
    "aria_qr_area_for": "QRコード: {text}",
    "aria_char_count": "文字数",
    "aria_save_btn": "現在のテキストを最近の一覧に保存",
    "aria_recent_panel": "最近のQRコード",
    "aria_recent_item": "最近の項目を読み込む: {text}",
    "aria_download_group": "QRコードをダウンロード",
    "aria_download_theme": "ダウンロードのカラーテーマ",
    "aria_download_png": "PNGでダウンロード",
    "aria_download_jpg": "JPGでダウンロード",
    "aria_download_svg": "SVGでダウンロード",
    "hint_save_shortcut": "保存するには Ctrl または Command キーと Enter を押してください。",
    "announce_saved": "最近の一覧に保存しました",
    "announce_loaded": "最近の項目を読み込みました"
  }
});
