I18N.register({
  "en": {
    "title": "Loan Repayment Calculator",
    "subtitle": "Equal principal / Equal principal+interest repayment",
    "method": "Repayment Method",
    "method_principal": "Equal Principal",
    "method_annuity": "Equal Principal + Interest",
    "loan_amount": "Loan Principal",
    "currency": "KRW",
    "add_1m": "+1M",
    "add_5m": "+5M",
    "add_10m": "+10M",
    "add_50m": "+50M",
    "reset": "Reset",
    "loan_term": "Loan Term (months)",
    "add_6mo": "+6mo",
    "add_1yr": "+1yr",
    "add_2yr": "+2yr",
    "add_3yr": "+3yr",
    "add_5yr": "+5yr",
    "grace_period": "Grace Period (months)",
    "interest_rate": "Annual Interest Rate (%)",
    "calculate": "Calculate",
    "monthly_principal": "Monthly Principal",
    "monthly_payment": "Monthly Payment",
    "total_interest": "Total Interest",
    "total_payment": "Total Payment",
    "schedule": "Amortization Schedule",
    "col_period": "#",
    "col_payment": "Payment",
    "col_principal": "Principal",
    "col_interest": "Interest",
    "col_cumulative": "Cumulative Principal",
    "col_balance": "Balance"
  },
  "ko": {
    "title": "대출 상환 계산기",
    "subtitle": "원금균등 / 원리금균등 상환",
    "method": "상환 방법",
    "method_principal": "원금균등상환",
    "method_annuity": "원리금균등상환",
    "loan_amount": "대출 원금",
    "currency": "원",
    "add_1m": "+100만",
    "add_5m": "+500만",
    "add_10m": "+1000만",
    "add_50m": "+5000만",
    "reset": "초기화",
    "loan_term": "대출 기간 (개월)",
    "add_6mo": "+6개월",
    "add_1yr": "+1년",
    "add_2yr": "+2년",
    "add_3yr": "+3년",
    "add_5yr": "+5년",
    "grace_period": "거치 기간 (개월)",
    "interest_rate": "연 이자율 (%)",
    "calculate": "계산하기",
    "monthly_principal": "월 납입 원금",
    "monthly_payment": "월 상환금 (원금+이자)",
    "total_interest": "총 이자",
    "total_payment": "총 상환액",
    "schedule": "상환 스케줄",
    "col_period": "회차",
    "col_payment": "상환금",
    "col_principal": "납입원금",
    "col_interest": "이자",
    "col_cumulative": "납입원금 누계",
    "col_balance": "잔금"
  },
  "jp": {
    "title": "ローン返済計算機",
    "subtitle": "元金均等 / 元利均等返済",
    "method": "返済方法",
    "method_principal": "元金均等返済",
    "method_annuity": "元利均等返済",
    "loan_amount": "借入元金",
    "currency": "円",
    "add_1m": "+100万",
    "add_5m": "+500万",
    "add_10m": "+1000万",
    "add_50m": "+5000万",
    "reset": "リセット",
    "loan_term": "借入期間（月）",
    "add_6mo": "+6ヶ月",
    "add_1yr": "+1年",
    "add_2yr": "+2年",
    "add_3yr": "+3年",
    "add_5yr": "+5年",
    "grace_period": "据置期間（月）",
    "interest_rate": "年利率（%）",
    "calculate": "計算する",
    "monthly_principal": "毎月元金返済額",
    "monthly_payment": "毎月返済額（元金+利息）",
    "total_interest": "利息合計",
    "total_payment": "返済総額",
    "schedule": "返済スケジュール",
    "col_period": "回",
    "col_payment": "返済額",
    "col_principal": "元金",
    "col_interest": "利息",
    "col_cumulative": "元金累計",
    "col_balance": "残高"
  }
});
