I18N.init({
  "en": {
    "title": "Day Info",
    "subtitle": "Solar / Lunar calendar conversion & holidays",
    "api_key": "API Key",
    "api_key_set": "API Key Set",
    "api_key_error": "API Key Error",
    "calendar": "Calendar",
    "solar": "Solar",
    "lunar": "Lunar",
    "year": "Year",
    "month": "Month",
    "day": "Day",
    "timezone": "Timezone",
    "week_count": "WeekCount",
    "week_3": "3 week",
    "week_5": "5 week",
    "week_7": "7 week",
    "leap": "Leap",
    "today": "Today",
    "epoch": "Epoch",
    "go": "Go",
    "epoch_placeholder": "e.g. 1744473600",
    "dow_short": [
      "Sun",
      "Mon",
      "Tue",
      "Wed",
      "Thu",
      "Fri",
      "Sat"
    ],
    "dow_full": [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday"
    ],
    "month_short": [
      "",
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec"
    ],
    "prompt_enter_key": "Enter your service key.\n(Encoded key from data.go.kr)",
    "prompt_edit_key": "Enter your service key.\n(Leave empty to remove the key.)",
    "error_year_range": "Year must be between 1 and 5000.",
    "error_invalid_epoch": "Invalid value. Please enter an integer (seconds).",
    "error_epoch_range": "Out of range. Must be between year 1 and year 5000 ({tz}).",
    "error_lunar_convert": "Unable to convert the given lunar date.",
    "label_solar": "Solar",
    "label_lunar": "Lunar",
    "label_timestamp": "Timestamp",
    "lunar_na": "N/A",
    "lunar_leap": " (Leap)",
    "lunar_approx": " (?)",
    "click_to_copy": "Click to copy",
    "copied": "Copied: {value}",
    "aria_selected": "(selected)",
    "aria_today": "(today)",
    "aria_date_input": "Date input",
    "aria_calendar_type": "Calendar type",
    "aria_year": "Year",
    "aria_month": "Month",
    "aria_day": "Day",
    "aria_timezone": "Timezone",
    "aria_week_count": "Week count",
    "aria_leap_month": "Leap month",
    "aria_date_nav": "Date navigation",
    "aria_prev_day": "Previous day",
    "aria_go_today": "Go to today",
    "aria_next_day": "Next day",
    "aria_api_key": "API service key settings",
    "aria_epoch": "Epoch timestamp",
    "aria_apply_epoch": "Apply epoch",
    "aria_weekly_calendar": "Weekly calendar"
  },
  "ko": {
    "title": "날짜 정보",
    "subtitle": "양력/음력 변환 및 공휴일 정보",
    "api_key": "API 키",
    "api_key_set": "API 키 설정됨",
    "api_key_error": "API 키 오류",
    "calendar": "달력",
    "solar": "양력",
    "lunar": "음력",
    "year": "연도",
    "month": "월",
    "day": "일",
    "timezone": "시간대",
    "week_count": "주간 수",
    "week_3": "3주",
    "week_5": "5주",
    "week_7": "7주",
    "leap": "윤달",
    "today": "오늘",
    "epoch": "Epoch",
    "go": "이동",
    "epoch_placeholder": "예: 1744473600",
    "dow_short": [
      "일",
      "월",
      "화",
      "수",
      "목",
      "금",
      "토"
    ],
    "dow_full": [
      "일요일",
      "월요일",
      "화요일",
      "수요일",
      "목요일",
      "금요일",
      "토요일"
    ],
    "month_short": [
      "",
      "1월",
      "2월",
      "3월",
      "4월",
      "5월",
      "6월",
      "7월",
      "8월",
      "9월",
      "10월",
      "11월",
      "12월"
    ],
    "prompt_enter_key": "서비스 키를 입력해주세요.\n(data.go.kr에서 발급받은 인코딩 키)",
    "prompt_edit_key": "서비스 키를 입력해주세요.\n(비워두면 키가 삭제됩니다.)",
    "error_year_range": "연도는 1년에서 5000년 사이여야 합니다.",
    "error_invalid_epoch": "잘못된 값입니다. 정수(초)를 입력해주세요.",
    "error_epoch_range": "범위를 벗어났습니다. 1년~5000년 사이여야 합니다 ({tz}).",
    "error_lunar_convert": "해당 음력 날짜를 변환할 수 없습니다.",
    "label_solar": "양력",
    "label_lunar": "음력",
    "label_timestamp": "타임스탬프",
    "lunar_na": "변환 불가",
    "lunar_leap": " (윤)",
    "lunar_approx": " (?)",
    "click_to_copy": "클릭하여 복사",
    "copied": "복사됨: {value}",
    "aria_selected": "(선택됨)",
    "aria_today": "(오늘)",
    "aria_date_input": "날짜 입력",
    "aria_calendar_type": "달력 종류",
    "aria_year": "연도",
    "aria_month": "월",
    "aria_day": "일",
    "aria_timezone": "시간대",
    "aria_week_count": "주간 수",
    "aria_leap_month": "윤달 여부",
    "aria_date_nav": "날짜 이동",
    "aria_prev_day": "이전 날짜",
    "aria_go_today": "오늘로 이동",
    "aria_next_day": "다음 날짜",
    "aria_api_key": "API 서비스 키 설정",
    "aria_epoch": "Epoch 타임스탬프",
    "aria_apply_epoch": "Epoch 적용",
    "aria_weekly_calendar": "주간 달력"
  },
  "jp": {
    "title": "日付情報",
    "subtitle": "太陽暦/太陰暦変換および祝日情報",
    "api_key": "APIキー",
    "api_key_set": "APIキー設定済",
    "api_key_error": "APIキーエラー",
    "calendar": "暦",
    "solar": "太陽暦",
    "lunar": "太陰暦",
    "year": "年",
    "month": "月",
    "day": "日",
    "timezone": "タイムゾーン",
    "week_count": "週数",
    "week_3": "3週間",
    "week_5": "5週間",
    "week_7": "7週間",
    "leap": "閏月",
    "today": "今日",
    "epoch": "Epoch",
    "go": "実行",
    "epoch_placeholder": "例: 1744473600",
    "dow_short": [
      "日",
      "月",
      "火",
      "水",
      "木",
      "金",
      "土"
    ],
    "dow_full": [
      "日曜日",
      "月曜日",
      "火曜日",
      "水曜日",
      "木曜日",
      "金曜日",
      "土曜日"
    ],
    "month_short": [
      "",
      "1月",
      "2月",
      "3月",
      "4月",
      "5月",
      "6月",
      "7月",
      "8月",
      "9月",
      "10月",
      "11月",
      "12月"
    ],
    "prompt_enter_key": "サービスキーを入力してください。\n（data.go.krで発行されたエンコードキー）",
    "prompt_edit_key": "サービスキーを入力してください。\n（空欄にするとキーが削除されます。）",
    "error_year_range": "年は1年から5000年の間でなければなりません。",
    "error_invalid_epoch": "無効な値です。整数（秒）を入力してください。",
    "error_epoch_range": "範囲外です。1年〜5000年の間でなければなりません ({tz})。",
    "error_lunar_convert": "指定された旧暦の日付を変換できません。",
    "label_solar": "太陽暦",
    "label_lunar": "太陰暦",
    "label_timestamp": "タイムスタンプ",
    "lunar_na": "変換不可",
    "lunar_leap": " (閏)",
    "lunar_approx": " (?)",
    "click_to_copy": "クリックでコピー",
    "copied": "コピー済: {value}",
    "aria_selected": "（選択中）",
    "aria_today": "（今日）",
    "aria_date_input": "日付入力",
    "aria_calendar_type": "暦の種類",
    "aria_year": "年",
    "aria_month": "月",
    "aria_day": "日",
    "aria_timezone": "タイムゾーン",
    "aria_week_count": "週数",
    "aria_leap_month": "閏月",
    "aria_date_nav": "日付移動",
    "aria_prev_day": "前の日",
    "aria_go_today": "今日に移動",
    "aria_next_day": "次の日",
    "aria_api_key": "APIサービスキー設定",
    "aria_epoch": "Epochタイムスタンプ",
    "aria_apply_epoch": "Epoch適用",
    "aria_weekly_calendar": "週間カレンダー"
  }
});
