I18N.init({
  "en": {
    "title": "Dice Expected Value Calculator",
    "expected_value": "Expected Value",
    "num_dice": "Number of Dice",
    "num_dice_hint": "How many dice to roll",
    "operation": "Operation",
    "operation_hint": "How to combine dice",
    "op_product": "Product",
    "op_sum": "Sum",
    "face_values": "Face Values",
    "face_values_hint": "Comma-separated",
    "range_label": "Range (start/end)",
    "range_hint": "Generate consecutive integers from start to end",
    "presets": "Presets",
    "preset_2d6": "2d6 — two standard dice",
    "preset_3d6": "3d6 — three standard dice",
    "preset_2d10": "2d10 — two 10-sided dice",
    "preset_1d20": "1d20 — one 20-sided dice",
    "preset_2d4": "2d4 — two 4-sided dice",
    "preset_2d12": "2d12 — two dodecahedral",
    "preset_4d12": "4d12 — four dodecahedral",
    "preset_custom": "3d[-1,1,2,3,4,6] — custom faces",
    "preset_primes": "2d[primes] — 12 prime faces",
    "preset_coin": "Coin × 3 — three coin flips",
    "all_outcomes": "All Possible Outcomes",
    "rank": "Rank",
    "count": "Count",
    "probability": "Probability",
    "distribution": "Distribution",
    "calculating": "Calculating...",
    "error_num_dice": "Please enter the number of dice (1~20).",
    "error_max_dice": "Maximum 20 dice allowed.",
    "dice_with": "dice with",
    "faces": "faces",
    "total_combinations": "total combinations",
    "unique_values": "unique products/sums",
    "too_many_compute": "Too many unique products/sums to compute",
    "try_fewer": "Try fewer dice or fewer face values.",
    "too_many_display": "Too many unique products/sums to display",
    "ev_shown_above": "The expected value is still shown above."
  },
  "ko": {
    "title": "주사위 기대값 계산기",
    "expected_value": "기대값",
    "num_dice": "주사위 수",
    "num_dice_hint": "굴릴 주사위 개수",
    "operation": "연산",
    "operation_hint": "주사위 결합 방식",
    "op_product": "곱",
    "op_sum": "합",
    "face_values": "면 값",
    "face_values_hint": "쉼표로 구분",
    "range_label": "범위 (시작/끝)",
    "range_hint": "시작부터 끝까지 연속 정수 생성",
    "presets": "프리셋",
    "preset_2d6": "2d6 — 표준 주사위 2개",
    "preset_3d6": "3d6 — 표준 주사위 3개",
    "preset_2d10": "2d10 — 10면체 주사위 2개",
    "preset_1d20": "1d20 — 20면체 주사위 1개",
    "preset_2d4": "2d4 — 4면체 주사위 2개",
    "preset_2d12": "2d12 — 12면체 2개",
    "preset_4d12": "4d12 — 12면체 4개",
    "preset_custom": "3d[-1,1,2,3,4,6] — 사용자 정의",
    "preset_primes": "2d[소수] — 소수 12면",
    "preset_coin": "동전 × 3 — 동전 던지기 3회",
    "all_outcomes": "가능한 모든 결과",
    "rank": "순위",
    "count": "횟수",
    "probability": "확률",
    "distribution": "분포",
    "calculating": "계산 중...",
    "error_num_dice": "주사위 수를 입력해주세요 (1~20).",
    "error_max_dice": "최대 20개까지 가능합니다.",
    "dice_with": "개의 주사위,",
    "faces": "면",
    "total_combinations": "전체 조합 수",
    "unique_values": "고유 곱/합 수",
    "too_many_compute": "고유 곱/합이 너무 많아 계산할 수 없습니다",
    "try_fewer": "주사위 수 또는 면 값을 줄여주세요.",
    "too_many_display": "고유 곱/합이 너무 많아 표시할 수 없습니다",
    "ev_shown_above": "기대값은 위에 표시되어 있습니다."
  },
  "jp": {
    "title": "サイコロ期待値計算機",
    "expected_value": "期待値",
    "num_dice": "サイコロの数",
    "num_dice_hint": "振るサイコロの個数",
    "operation": "演算",
    "operation_hint": "サイコロの結合方法",
    "op_product": "積",
    "op_sum": "和",
    "face_values": "面の値",
    "face_values_hint": "カンマ区切り",
    "range_label": "範囲（開始/終了）",
    "range_hint": "開始から終了まで連続整数を生成",
    "presets": "プリセット",
    "preset_2d6": "2d6 — 標準サイコロ2個",
    "preset_3d6": "3d6 — 標準サイコロ3個",
    "preset_2d10": "2d10 — 10面サイコロ2個",
    "preset_1d20": "1d20 — 20面サイコロ1個",
    "preset_2d4": "2d4 — 4面サイコロ2個",
    "preset_2d12": "2d12 — 12面体2個",
    "preset_4d12": "4d12 — 12面体4個",
    "preset_custom": "3d[-1,1,2,3,4,6] — カスタム面",
    "preset_primes": "2d[素数] — 素数12面",
    "preset_coin": "コイン × 3 — コイントス3回",
    "all_outcomes": "すべての結果",
    "rank": "順位",
    "count": "回数",
    "probability": "確率",
    "distribution": "分布",
    "calculating": "計算中...",
    "error_num_dice": "サイコロの数を入力してください（1〜20）。",
    "error_max_dice": "最大20個までです。",
    "dice_with": "個のサイコロ、",
    "faces": "面",
    "total_combinations": "全組み合わせ数",
    "unique_values": "固有の積/和の数",
    "too_many_compute": "固有の積/和が多すぎて計算できません",
    "try_fewer": "サイコロの数または面の値を減らしてください。",
    "too_many_display": "固有の積/和が多すぎて表示できません",
    "ev_shown_above": "期待値は上に表示されています。"
  }
});
