I18N.register({
  "en": {
    "title": "RGB Color Picker",
    "subtitle": "Adjust color using the sliders",
    "red": "RED",
    "green": "GREEN",
    "blue": "BLUE",
    "rgb": "RGB",
    "cmy": "CMY",
    "hsb": "HSB",
    "click_to_copy": "Click to copy",
    "complementary": "Complementary",
    "closest_name": "Closest Color Name",
    "similar_10": "10 Similar Colors",
    "copied": "Copied to clipboard!",
    "exact_match": "Exact match!",
    "distance_prefix": "Distance: ",
    "distance_suffix": " (closer = more similar)"
  },
  "ko": {
    "title": "RGB 색상 피커",
    "subtitle": "슬라이더를 움직여 색상을 조절하세요",
    "red": "빨강",
    "green": "초록",
    "blue": "파랑",
    "rgb": "RGB",
    "cmy": "CMY",
    "hsb": "HSB",
    "click_to_copy": "클릭하여 복사",
    "complementary": "보색",
    "closest_name": "가장 가까운 색상 이름",
    "similar_10": "유사한 색상 10개",
    "copied": "클립보드에 복사되었습니다!",
    "exact_match": "정확히 일치!",
    "distance_prefix": "거리: ",
    "distance_suffix": " (가까울수록 유사)"
  },
  "jp": {
    "title": "RGBカラーピッカー",
    "subtitle": "スライダーで色を調整してください",
    "red": "赤",
    "green": "緑",
    "blue": "青",
    "rgb": "RGB",
    "cmy": "CMY",
    "hsb": "HSB",
    "click_to_copy": "クリックでコピー",
    "complementary": "補色",
    "closest_name": "最も近い色名",
    "similar_10": "類似色10色",
    "copied": "クリップボードにコピーしました！",
    "exact_match": "完全一致！",
    "distance_prefix": "距離: ",
    "distance_suffix": "（近いほど類似）"
  }
});
