I18N.register({
  "en": {
    "title": "Exchange Rate Calculator",
    "subtitle": "Convert an amount to all world currencies",
    "label_amount": "AMOUNT",
    "currency_unit": "KRW",
    "label_search": "SEARCH",
    "placeholder_search": "Search by code or name (USD, Dollar...)",
    "col_code": "Code",
    "col_name": "Currency",
    "col_amount": "Amount",
    "loading": "Loading...",
    "error_load": "Failed to load exchange rate data.",
    "date_prefix": "Reference date: ",
    "no_results": "No currencies match your search.",
    "aria_main": "Exchange rate calculator",
    "aria_amount": "Amount in KRW to convert",
    "aria_search": "Filter currencies by code or name",
    "aria_table": "Exchange rate results",
    "aria_status": "Loading status"
  },
  "ko": {
    "title": "환율 계산기",
    "subtitle": "원화 금액을 전 세계 통화로 환산합니다",
    "label_amount": "금액",
    "currency_unit": "원",
    "label_search": "검색",
    "placeholder_search": "코드 또는 통화명 검색 (USD, Dollar...)",
    "col_code": "통화 코드",
    "col_name": "통화명",
    "col_amount": "금액",
    "loading": "로딩 중...",
    "error_load": "환율 데이터를 불러오지 못했습니다.",
    "date_prefix": "기준 날짜: ",
    "no_results": "검색 결과가 없습니다.",
    "aria_main": "환율 계산기",
    "aria_amount": "환산할 원화 금액",
    "aria_search": "통화 코드 또는 이름으로 검색",
    "aria_table": "환율 결과 표",
    "aria_status": "로딩 상태"
  },
  "jp": {
    "title": "為替レート計算機",
    "subtitle": "ウォン建ての金額を世界中の通貨に換算します",
    "label_amount": "金額",
    "currency_unit": "ウォン",
    "label_search": "検索",
    "placeholder_search": "コードまたは通貨名で検索 (USD, Dollar...)",
    "col_code": "通貨コード",
    "col_name": "通貨名",
    "col_amount": "金額",
    "loading": "読み込み中...",
    "error_load": "為替レートデータを読み込めませんでした。",
    "date_prefix": "基準日: ",
    "no_results": "検索結果がありません。",
    "aria_main": "為替レート計算機",
    "aria_amount": "換算するウォンの金額",
    "aria_search": "通貨コードまたは名前で絞り込む",
    "aria_table": "為替レート結果テーブル",
    "aria_status": "読み込み状態"
  }
});
